workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build for iOS Simulator
        script: flutter build ios --simulator

      - name: Zip .app for Appetize.io
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphonesimulator
          zip -r ../../ipa/Runner.app.zip Runner.app

    artifacts:
      - build/ios/ipa/Runner.app.zip
