workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build for iOS Simulator
        script: flutter build ios --simulator

      - name: Inspect simulator build output and zip Runner.app
        script: |
          echo "📁 Explorando contenido en build/ios/iphonesimulator:"
          if [ -d build/ios/iphonesimulator ]; then
            ls -la build/ios/iphonesimulator
          else
            echo "❌ La carpeta iphonesimulator no existe."
            exit 1
          fi

          if [ -d build/ios/iphonesimulator/Runner.app ]; then
            echo "✅ Runner.app encontrado. Procediendo a comprimir."
            mkdir -p build/ios/ipa
            cd build/ios/iphonesimulator
            zip -r ../../ipa/Runner.app.zip Runner.app
            echo "✅ Runner.app.zip creado exitosamente."
          else
            echo "❌ Runner.app NO fue encontrado. Puede que el build haya fallado."
            exit 1
          fi

    artifacts:
      - build/ios/ipa/Runner.app.zip
