workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build for iOS Simulator
        script: flutter build ios --simulator

      - name: Zip .app for Appetize.io
        script: |
          echo "📁 Contenido de build/ios/iphonesimulator:"
          ls -la build/ios/iphonesimulator

          if [ -d build/ios/iphonesimulator/Runner.app ]; then
            mkdir -p build/ios/ipa
            cd build/ios/iphonesimulator
            zip -r ../../ipa/Runner.app.zip Runner.app
            echo "✅ Runner.app.zip creado exitosamente."
          else
            echo "❌ Runner.app no encontrado. Fallo al compilar para simulador."
            exit 1
          fi
    
    artifacts:
      - build/ios/ipa/Runner.app.zip
